name: Bitrise Xcode Check and Update
on:
  schedule:
  - cron: 0 */6 * * *
jobs:
  build:
    needs:
    - up
    runs-on:
    - self-hosted
    - "${{ needs.up.outputs.vm-name }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r ./test-fixtures/requirements.txt

        '
    - name: Modify bitrise.yml
      run: 'python ./test-fixtures/update.py

        '
    - name: Commit and push if bitrise.yml changed
      run: 'git diff

        git config --global user.email "firefox-test-engineering@mozilla.com"

        git config --global user.name "Firefox Test Engineering"

        git diff --quiet || (git add bitrise.yml)'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: update-br-new-xcode-version
        commit-message: Auto Update Bitrise.YML
        committer: GitHub <noreply@github.com>
        title: Update Bitrise NewXcodeVersions Workflow Xcode Stack
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version:
        - 3.7
      max-parallel: 4
  down:
    if: always()
    needs:
    - up
    - build
    runs-on: ubuntu-latest
    steps:
    - id: down
      name: down
      uses: jeff-vincent/orka-actions-down-org@1.0.0
      with:
        githubOrg: example-org-1
        githubPat: ${{ secrets.GH_PAT }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        orkaUser: ${{ secrets.ORKA_USER }}
        vmName: ${{ needs.job1.outputs.vm-name }}
        vpnAddress: ${{ secrets.VPN_ADDRESS }}
        vpnPassword: ${{ secrets.VPN_PASSWORD }}
        vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
        vpnUser: ${{ secrets.VPN_USER }}
  up:
    outputs:
      vm-name: ${{ steps.up.outputs.vm-name }}
    runs-on: ubuntu-latest
    steps:
    - id: up
      name: up
      uses: jeff-vincent/orka-actions-up-org@1.0.0
      with:
        coreCount: 3
        githubOrg: example-org-1
        githubPat: ${{ secrets.GH_PAT }}
        orkaBaseImage: gha-org-agent.img
        orkaPass: ${{ secrets.ORKA_PASS }}
        orkaUser: ${{ secrets.ORKA_USER }}
        vcpuCount: 3
        vpnAddress: ${{ secrets.VPN_ADDRESS }}
        vpnPassword: ${{ secrets.VPN_PASSWORD }}
        vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
        vpnUser: ${{ secrets.VPN_USER }}
